CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_HID_KEYBOARD=y
CONFIG_ZMK_KSCAN_GPIO_KEYS=y

CONFIG_ZMK_KSCAN_MATRIX=n
CONFIG_ZMK_KSCAN_VIRTUAL_MATRIX=n
# main分支关键：同时开启USB+BLE，允许USB插着蓝牙也广播
CONFIG_ZMK_USB_BLE_SIMULTANEOUS=y
