# kscan消抖，单位ms
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS=30
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE=70

CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_HID_KEYBOARD=y
CONFIG_ZMK_KSCAN_VIRTUAL_MATRIX=y

# 关闭旧gpio‑keys驱动（本方案不再使用gpio‑keys）
CONFIG_ZMK_KSCAN_GPIO_KEYS=n
