# 导电胶按键消抖 15ms
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=15
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=15

CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_BATTERY_READING=y
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_RESET=n

# 开启组合键(combo)功能
CONFIG_ZMK_COMBOS=y
