# 基础功能开启
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_WAKEUP=y
CONFIG_ZMK_SLEEP=y
CONFIG_IDLE_SLEEP_TIMEOUT=30000
CONFIG_CONSOLE=n
CONFIG_SERIAL=n

# 全局开启引脚内部上拉（不用外接电阻）
CONFIG_GPIO_PULLUP_DEFAULT=y

# ========== 导电胶按键专属消抖参数（重点） ==========
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=18
CONFIG_ZMK_KSCAN_POLL_PERIOD_MS=10
# ===================================================

# 蓝牙快捷按键
# LShift+LCtrl+J 长按3秒：进入蓝牙配对
CONFIG_ZMK_BLE_PAIRING_BINDING=(&mkp TAB W S)
# LShift+LCtrl+P 长按3秒：清空所有蓝牙配对
CONFIG_ZMK_BLE_CLEAR_PROFILES_BINDING=(&mkp TAB A D)

CONFIG_ZMK_BATTERY=n
