CONFIG_BOARD_NICE_NANO_V2=y

# 蓝牙
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_REQUEST=y
CONFIG_ZMK_BLE_AUTO_CONNECT=y

# USB自动切换
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_AUTO_DETECT=y

# 休眠低功耗
CONFIG_SYS_PM=y
CONFIG_SYS_PM_STATE_1=y
CONFIG_SYS_PM_STATE_2=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=30000

# BLE广播间隔，降低功耗
CONFIG_ZMK_BLE_ADV_INTERVAL_MIN=0x0640
CONFIG_ZMK_BLE_ADV_INTERVAL_MAX=0x07D0

# 关闭无用外设，省电
CONFIG_SPI=n
CONFIG_I2C=n
CONFIG_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_LOG=n
CONFIG_LOG_DEFAULT_LEVEL_NONE=y

# GPIO独立键盘扫描间隔
CONFIG_ZMK_GPIO_KEY_SCAN_INTERVAL_MS=1

# 开启组合键combo
CONFIG_ZMK_COMBO=y
