name: Build ZMK Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ZMK Firmware
        uses: zmkfirmware/actions/build@v2
        with:
          zmk_ref: v0.15.0
          config_path: ${{ github.workspace }}
