name: Build Firmware
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: promicro_nrf52840
      shield: gamepad
