name: Build Firmware
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build firmware
        uses: zmkfirmware/zmk-build-action@v2
        with:
          board: promicro_nrf52840
          shield: gamepad
          # 关闭那个导致qualifiers报错的冗余硬件校验
          extra_args: --no-sysbuild-check

