name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    strategy:
      matrix:
        board:
          - nicenano_v2
        shield:
          - my_12key
    with:
      board: ${{ matrix.board }}
      shield: ${{ matrix.shield }}
